"""Known character / celebrity dictionary for CLIP zero-shot recognition.

Each entry is (display_name, franchise, media_type, clip_description).
- display_name:     What appears in titles and tags.
- franchise:        Series / franchise name (empty string if solo).
- media_type:       One of "anime", "game", "movie", "tv", "comic", "cartoon",
                    "celebrity", or "".
- clip_description: Natural-language prompt for CLIP matching.  More visual
                    detail → better accuracy.
"""

KNOWN_CHARACTERS = [
    # ── Superheroes (Marvel) ──────────────────────────────────────────
    ("Spider-Man", "Marvel", "comic",
     "Spider-Man superhero in red and blue suit with web pattern and mask"),
    ("Iron Man", "Marvel", "comic",
     "Iron Man superhero in red and gold metal armored suit"),
    ("Captain America", "Marvel", "comic",
     "Captain America superhero with red white and blue shield"),
    ("Thor", "Marvel", "comic",
     "Thor superhero with long hair hammer and red cape"),
    ("Hulk", "Marvel", "comic",
     "The Hulk large green muscular superhero"),
    ("Black Widow", "Marvel", "comic",
     "Black Widow red-haired female superhero in black suit"),
    ("Deadpool", "Marvel", "comic",
     "Deadpool in red and black suit with mask and swords"),
    ("Wolverine", "Marvel", "comic",
     "Wolverine X-Men character with metal claws and yellow suit"),
    ("Black Panther", "Marvel", "comic",
     "Black Panther superhero in black vibranium suit"),
    ("Thanos", "Marvel", "comic",
     "Thanos purple-skinned villain with golden infinity gauntlet"),
    ("Venom", "Marvel", "comic",
     "Venom black alien symbiote creature with white spider symbol and teeth"),
    ("Doctor Strange", "Marvel", "comic",
     "Doctor Strange sorcerer with red cloak and magic circles"),

    # ── Superheroes (DC) ──────────────────────────────────────────────
    ("Batman", "DC", "comic",
     "Batman dark knight superhero in black cape and cowl"),
    ("Superman", "DC", "comic",
     "Superman superhero in blue suit with red cape and S symbol on chest"),
    ("Wonder Woman", "DC", "comic",
     "Wonder Woman superhero with tiara golden lasso and armor"),
    ("The Flash", "DC", "comic",
     "The Flash superhero in red suit with lightning bolt symbol"),
    ("Aquaman", "DC", "comic",
     "Aquaman superhero with trident and golden armor"),
    ("Joker", "DC", "comic",
     "The Joker villain with green hair white face and purple suit"),
    ("Harley Quinn", "DC", "comic",
     "Harley Quinn with colorful pigtails and baseball bat"),

    # ── Disney / Pixar ────────────────────────────────────────────────
    ("Mickey Mouse", "Disney", "cartoon",
     "Mickey Mouse cartoon character with round black ears and red shorts"),
    ("Donald Duck", "Disney", "cartoon",
     "Donald Duck cartoon character with blue sailor outfit"),
    ("Elsa", "Frozen", "movie",
     "Elsa from Frozen with platinum blonde braid and blue ice dress"),
    ("Anna", "Frozen", "movie",
     "Anna from Frozen with auburn hair braids and winter dress"),
    ("Cinderella", "Disney", "movie",
     "Cinderella Disney princess in sparkly blue ball gown"),
    ("Ariel", "The Little Mermaid", "movie",
     "Ariel Disney mermaid princess with long red hair and green tail"),
    ("Rapunzel", "Tangled", "movie",
     "Rapunzel Disney princess with very long golden hair"),
    ("Moana", "Disney", "movie",
     "Moana Disney princess from Polynesia with curly dark hair"),
    ("Simba", "The Lion King", "movie",
     "Simba the lion from The Lion King"),
    ("Buzz Lightyear", "Toy Story", "movie",
     "Buzz Lightyear astronaut space ranger from Toy Story"),
    ("Woody", "Toy Story", "movie",
     "Woody cowboy character from Toy Story with hat and vest"),
    ("Stitch", "Lilo & Stitch", "movie",
     "Stitch small blue alien creature from Lilo and Stitch"),
    ("Baby Yoda", "Star Wars", "movie",
     "Baby Yoda Grogu small green creature from The Mandalorian"),
    ("Darth Vader", "Star Wars", "movie",
     "Darth Vader Star Wars villain in black armor and mask"),

    # ── Anime ─────────────────────────────────────────────────────────
    ("Goku", "Dragon Ball", "anime",
     "Goku from Dragon Ball with spiky black hair and orange fighting outfit"),
    ("Vegeta", "Dragon Ball", "anime",
     "Vegeta from Dragon Ball with spiky upward hair and blue suit"),
    ("Naruto", "Naruto", "anime",
     "Naruto Uzumaki anime ninja with blonde spiky hair orange outfit and headband"),
    ("Sasuke", "Naruto", "anime",
     "Sasuke Uchiha from Naruto with dark hair and dark outfit"),
    ("Kakashi", "Naruto", "anime",
     "Kakashi Hatake from Naruto ninja with silver hair and face mask"),
    ("Itachi", "Naruto", "anime",
     "Itachi Uchiha from Naruto with red Sharingan eyes and black cloak"),
    ("Sakura", "Naruto", "anime",
     "Sakura Haruno from Naruto anime girl with pink hair"),
    ("Hinata", "Naruto", "anime",
     "Hinata Hyuga from Naruto anime girl with dark purple hair"),
    ("Luffy", "One Piece", "anime",
     "Monkey D Luffy from One Piece anime pirate with straw hat and scar"),
    ("Zoro", "One Piece", "anime",
     "Roronoa Zoro from One Piece anime swordsman with green hair and three swords"),
    ("Levi", "Attack on Titan", "anime",
     "Levi Ackerman from Attack on Titan anime soldier with short black hair"),
    ("Eren", "Attack on Titan", "anime",
     "Eren Yeager from Attack on Titan anime character with brown hair"),
    ("Mikasa", "Attack on Titan", "anime",
     "Mikasa Ackerman from Attack on Titan anime girl with black hair and red scarf"),
    ("Tanjiro", "Demon Slayer", "anime",
     "Tanjiro Kamado from Demon Slayer anime boy with scar earrings and checkered haori"),
    ("Nezuko", "Demon Slayer", "anime",
     "Nezuko Kamado from Demon Slayer anime girl with bamboo muzzle and pink eyes"),
    ("Gojo", "Jujutsu Kaisen", "anime",
     "Gojo Satoru from Jujutsu Kaisen anime character with white hair and blindfold"),
    ("Deku", "My Hero Academia", "anime",
     "Izuku Midoriya Deku from My Hero Academia anime character with curly green hair"),
    ("Todoroki", "My Hero Academia", "anime",
     "Todoroki Shoto from My Hero Academia with half red half white hair"),
    ("Saitama", "One Punch Man", "anime",
     "Saitama from One Punch Man bald anime character in yellow suit and cape"),
    ("Genos", "One Punch Man", "anime",
     "Genos from One Punch Man anime cyborg with blonde hair and metal body"),
    ("Zero Two", "Darling in the Franxx", "anime",
     "Zero Two from Darling in the Franxx anime girl with pink hair and red horns"),
    ("Rem", "Re:Zero", "anime",
     "Rem from Re Zero anime maid with blue hair and hair ornament"),
    ("Sailor Moon", "Sailor Moon", "anime",
     "Sailor Moon anime magical girl with blonde pigtails and tiara"),
    ("Spike Spiegel", "Cowboy Bebop", "anime",
     "Spike Spiegel from Cowboy Bebop with fluffy dark hair and suit"),
    ("Light Yagami", "Death Note", "anime",
     "Light Yagami from Death Note anime character with brown hair holding notebook"),
    ("Violet Evergarden", "Violet Evergarden", "anime",
     "Violet Evergarden anime girl with blonde hair and mechanical hands"),
    ("Anya Forger", "Spy x Family", "anime",
     "Anya Forger from Spy x Family anime girl with pink hair and hair ornaments"),
    ("Power", "Chainsaw Man", "anime",
     "Power from Chainsaw Man anime girl with blonde hair and horns"),
    ("Denji", "Chainsaw Man", "anime",
     "Denji from Chainsaw Man anime boy with chainsaw coming from head"),
    ("Frieren", "Frieren", "anime",
     "Frieren the elf anime girl with long white hair and pointed ears"),
    ("Totoro", "My Neighbor Totoro", "anime",
     "Totoro large gray fluffy forest spirit from Studio Ghibli"),
    ("No Face", "Spirited Away", "anime",
     "No Face from Spirited Away black masked spirit from Studio Ghibli"),

    # ── Pokémon ───────────────────────────────────────────────────────
    ("Pikachu", "Pokémon", "anime",
     "Pikachu yellow electric mouse Pokemon with red cheeks and lightning tail"),
    ("Charizard", "Pokémon", "anime",
     "Charizard orange dragon fire Pokemon with wings and flame tail"),
    ("Eevee", "Pokémon", "anime",
     "Eevee brown fluffy fox-like Pokemon with big ears"),
    ("Mewtwo", "Pokémon", "anime",
     "Mewtwo purple psychic legendary Pokemon"),
    ("Gengar", "Pokémon", "anime",
     "Gengar purple ghost Pokemon with wide grin"),

    # ── Video Games ───────────────────────────────────────────────────
    ("Mario", "Super Mario", "game",
     "Super Mario Nintendo character with red hat big mustache and overalls"),
    ("Luigi", "Super Mario", "game",
     "Luigi Nintendo character with green hat and mustache"),
    ("Link", "The Legend of Zelda", "game",
     "Link from Zelda character with green tunic pointed ears and sword"),
    ("Zelda", "The Legend of Zelda", "game",
     "Princess Zelda from Legend of Zelda with pointed ears and tiara"),
    ("Master Chief", "Halo", "game",
     "Master Chief from Halo in green Spartan armor and gold visor helmet"),
    ("Kratos", "God of War", "game",
     "Kratos from God of War muscular bald man with red face markings and axe"),
    ("Geralt", "The Witcher", "game",
     "Geralt of Rivia from The Witcher with white hair scar and two swords"),
    ("Cloud", "Final Fantasy", "game",
     "Cloud Strife from Final Fantasy VII with spiky blonde hair and buster sword"),
    ("Sonic", "Sonic", "game",
     "Sonic the Hedgehog blue cartoon hedgehog with red shoes"),
    ("Kirby", "Kirby", "game",
     "Kirby small round pink Nintendo character"),
    ("Samus", "Metroid", "game",
     "Samus Aran from Metroid in orange power suit armor"),
    ("Pac-Man", "Pac-Man", "game",
     "Pac-Man yellow circle character eating dots"),
    ("Lara Croft", "Tomb Raider", "game",
     "Lara Croft from Tomb Raider woman with ponytail and dual pistols"),
    ("2B", "NieR Automata", "game",
     "2B from NieR Automata female android with white hair and black blindfold"),
    ("Arthur Morgan", "Red Dead Redemption", "game",
     "Arthur Morgan cowboy from Red Dead Redemption with hat"),
    ("Minecraft Steve", "Minecraft", "game",
     "Minecraft Steve blocky pixel character with pickaxe"),
    ("Creeper", "Minecraft", "game",
     "Minecraft Creeper green blocky pixel monster"),

    # ── Cartoons ──────────────────────────────────────────────────────
    ("SpongeBob", "SpongeBob SquarePants", "cartoon",
     "SpongeBob SquarePants yellow cartoon sponge character with square pants"),
    ("Patrick Star", "SpongeBob SquarePants", "cartoon",
     "Patrick Star pink starfish from SpongeBob SquarePants"),
    ("Homer Simpson", "The Simpsons", "cartoon",
     "Homer Simpson bald yellow cartoon character with white shirt"),
    ("Bart Simpson", "The Simpsons", "cartoon",
     "Bart Simpson yellow cartoon boy with spiky hair"),
    ("Rick Sanchez", "Rick and Morty", "cartoon",
     "Rick from Rick and Morty cartoon scientist with blue spiky hair and lab coat"),
    ("Morty Smith", "Rick and Morty", "cartoon",
     "Morty from Rick and Morty cartoon boy with yellow shirt"),
    ("Shrek", "Shrek", "movie",
     "Shrek large green cartoon ogre with vest"),
    ("Grinch", "Dr. Seuss", "movie",
     "The Grinch green furry creature from How the Grinch Stole Christmas"),
    ("Scooby-Doo", "Scooby-Doo", "cartoon",
     "Scooby-Doo brown cartoon Great Dane dog with collar"),
    ("Tom and Jerry", "Tom and Jerry", "cartoon",
     "Tom and Jerry cartoon cat and mouse"),
    ("Finn", "Adventure Time", "cartoon",
     "Finn from Adventure Time cartoon boy with white bear hat"),
    ("Jake", "Adventure Time", "cartoon",
     "Jake the dog from Adventure Time yellow stretchy cartoon dog"),
    ("Gumball", "Gumball", "cartoon",
     "Gumball blue cartoon cat from Amazing World of Gumball"),

    # ── Celebrities / Athletes ────────────────────────────────────────
    ("Tom Brady", "", "celebrity",
     "Tom Brady American football quarterback in NFL uniform"),
    ("LeBron James", "", "celebrity",
     "LeBron James basketball player in NBA jersey"),
    ("Michael Jordan", "", "celebrity",
     "Michael Jordan basketball player in Chicago Bulls jersey number 23"),
    ("Kobe Bryant", "", "celebrity",
     "Kobe Bryant basketball player in Los Angeles Lakers jersey"),
    ("Stephen Curry", "", "celebrity",
     "Stephen Curry basketball player shooting three pointer"),
    ("Cristiano Ronaldo", "", "celebrity",
     "Cristiano Ronaldo soccer football player"),
    ("Lionel Messi", "", "celebrity",
     "Lionel Messi soccer football player"),
    ("Neymar", "", "celebrity",
     "Neymar soccer football player with styled hair"),
    ("Serena Williams", "", "celebrity",
     "Serena Williams female tennis player"),
    ("Mike Tyson", "", "celebrity",
     "Mike Tyson boxer with face tattoo"),
    ("Conor McGregor", "", "celebrity",
     "Conor McGregor MMA UFC fighter with beard and tattoos"),
    ("Taylor Swift", "", "celebrity",
     "Taylor Swift female pop singer and musician"),
    ("Beyoncé", "", "celebrity",
     "Beyoncé female pop singer and performer"),
    ("Drake", "", "celebrity",
     "Drake male rapper and musician"),
    ("Eminem", "", "celebrity",
     "Eminem Slim Shady white male rapper"),
    ("Billie Eilish", "", "celebrity",
     "Billie Eilish young female singer with colored hair"),
    ("Keanu Reeves", "", "celebrity",
     "Keanu Reeves actor with dark hair and beard"),
    ("Dwayne Johnson", "", "celebrity",
     "Dwayne The Rock Johnson muscular bald actor"),
    ("Robert Downey Jr", "", "celebrity",
     "Robert Downey Jr actor with goatee"),
    ("Johnny Depp", "", "celebrity",
     "Johnny Depp actor as Captain Jack Sparrow pirate"),
    ("Elon Musk", "", "celebrity",
     "Elon Musk tech businessman and entrepreneur"),

    # ── Generic baselines (absorb probability from non-character images) ──
    ("_generic_person", "", "",
     "a person standing or sitting"),
    ("_generic_animal", "", "",
     "an animal in nature"),
    ("_generic_landscape", "", "",
     "a landscape with mountains or water"),
    ("_generic_building", "", "",
     "a building or city skyline"),
    ("_generic_abstract", "", "",
     "an abstract colorful pattern or design"),
    ("_generic_car", "", "",
     "a car or vehicle"),
    ("_generic_food", "", "",
     "food on a plate or table"),
]
